### ISSUE TITLE
Suggestion: Ability to toggle "Monitor Technology" and "Max Framerate" setting in Nvidia drivers

### ISSUE THREAD

**Issue by GammaLyrae** [Maassoft/ColorControl#97]
Great app. 

The purpose of this would be to make it easier to optimize the display for different kinds of content. I like to use the BFI mode primarily for games that can lock and be stable at 60fps/120fps, but BFI isn't appropriate for all content (examples: 23/24/25/30fps or other low framerate media, emulators such as MAME, etc.). 

The way the driver / TV end up operating as it stands, if you turn Gsync "OFF" in your driver (Manage 3D settings -> Monitor Technology -> Fixed Refresh), you can then go into the TV setting, turn BFI on (might be in "Game Optimizer" depending on exactly which year TV you have) to your desired setting. Then, back in the driver, you can toggle "Monitor Technology" back to GSYNC, then "Set-Up Gsync ->Enable G-sync, G-sync compatible". From here, switching "Monitor Technology" to "Fixed Refresh" will go back to your last used, non-GSYNC settings on the TV (in this case, BFI), and turning the "Monitor Technology" back to "G-sync Compatible" will turn off BFI and re-enable Gsync with no remote inputs required. "Max Framerate" comes into play here as well; for VRR you want something just under your maximum refresh rate (ie, 118 for 120hz) to optimize for lowest input lag + no tearing, but for BFI, you want it to be locked to the maximum refresh of your display (typically easy enough to manage with Vsync, so long as the "Max Framerate" setting in the driver is set to "Off")

I think if the "Monitor Technology" and "Max Framerate" setting is put into the "Nvidia Controller Tab", you should be able to create a macro that includes a series of remote inputs to adjust the OLED Light setting as preferred without any other additional changes to the app or its function.

My end goal would be the ability to create shortcuts to enable combinations of driver / TV settings like this, or have them trigger upon the detection of certain programs (ie, revert to the appropriate 60hz mode for fixed refresh games + BFI, then go back to the last used profile or a selected profile after that game has closed):

120hz HDR RGB 10bit "Fixed Refresh" (For BFI)
60hz HDR RGB 10bit "Fixed Refresh" (For BFI)
120hz HDR RGB 10bit "Gsync-Compatible",  (For VRR) <-- Leaving "OLED Light" Maxed for this and the others above, since 100 is appropriate for HDR

120hz SDR RGB 10bit "Fixed Refresh", an LG controller setting to adjust "OLED Light" to max if it's not already there (For BFI)
60hz SDR RGB 10bit "Fixed Refresh" an LG controller setting to adjust "OLED Light" to max if it's not already there(For BFI)
120hz SDR RGB 10bit "Gsync-Compatible", an LG controller setting to reduce "OLED Light" to a comfortable level (For VRR)

**Comment by Maassoft** [comment]
Thanks for the detailed description of your issue.

I as well like to use BFI for games that run stably at 120fps, but a lot of games are simply to heavy to be able to reach 120fps constantly. In that case you want to use VRR. Unfortunately my C9 has a weird issue that it does not "understand" VRR when in HDMI 2.1 FRL mode. Only in the old HDMI 2.0 TDMS mode the "Instant game response has launched" popup shows and it is working then, but of course only up to 60fps at 4k. That's maybe one of the reasons I've not yet build in a switch to easily enable/disable GSYNC, because I've simple disabled it via the EDID of my C9 altogether (to prevent weird "spit screens", where half or a quarter of the screen turns black).

Another reason is that the NvApiWrapper I'm using does not support it yet, so I'll have to manually look up and "load" the functions of the NvApi that can be used for GSYNC. It sure can be done, but it just takes some more research time before I can get started adding functionality to ColorControl. Maybe I could even build in something like the Nvidia Profile Inspector, where you can adjust a lot of driver settings.

I think manually activating such preset would be the easiest way, because the current detecting algorithm is probably too late with changing settings. Once a program (game) has started, changing settings in the Nvidia control panel seem to have no effect.

I'll take this issue under consideration and maybe it'll be featured in a new version of ColorControl.

**Comment by GammaLyrae** [comment]
Good to know. I think "Max Framerate" NV Control Panel hook is probably the least important element of my request - This is easy enough to adjust on a per-game basis directly in the 3D settings profiles, or in a third party app like RTSS in cases where that doesn't work for some reason. Being able to hook into the Monitor Technology setting would more or less complete the app for me.

**Comment by Maassoft** [comment]
I've just released v6.0.0.0 which allows you to change some driver settings, including whether G-SYNC is enabled or not.

**Comment by GammaLyrae** [comment]
Nice!

I did some testing.

Windows 10, latest build (21h2)
Nvidia Driver 512.77 (also tested 512.59

Toggling Gsync works exactly once. Taking this action (turning it on or off) seems to crash at least one element of the driver.

![image](https://user-images.githubusercontent.com/97659643/169668664-e9c53da8-a5e5-45c2-885e-afff68a1cfab.png)

Notice that in the Nvidia control panel, most of the options are now missing

![image](https://user-images.githubusercontent.com/97659643/169668673-3d54264e-b669-41cf-9ab9-d340866ca48e.png)

Rebooting the driver (via CRU) or rebooting the PC restores it to normal functionality, but the problem is repeatable.

**Comment by Maassoft** [comment]
I'm using the exact same driver version (DCH as well) and haven't seen such strange behavior.
There's an issue though, if you use spaces in the name of a Nvidia preset, then you get the "Error while executing steps: Requested value 'NvPreset' was not found." if you use it in the steps of the LG controller.
What happens if you just switch between the Nvidia presets? I'm using these (GSYNC disabled/enabled) and haven't seen a driver crash or weird behavior:
![image](https://user-images.githubusercontent.com/70057942/169669352-aa8d9e3a-b3c1-41b0-927d-ecca2a19ecf7.png)
Note that I'm only using driver settings in these presets, do you change more settings in your presets?

**Comment by GammaLyrae** [comment]
Hm. Yep! I was making the changes via an LG Controller macro, and the Nvidia presets had spaces. I tried just double clicking the NV Controller presets and was still experiencing the issue, but I went through some sensible troubleshooting steps (unplugging a secondary monitor I wasn't actively using, restarting my PC), and I get the expected behavior, now.

Well done! Thank you so much for this addition to the software. It feels trivially easy to optimize my display for different contents now.

**Comment by Maassoft** [comment]
Thanks! It will take a while to optimize it all, I was only able to test it on one system.
By the way, I said "spaces", but I really meant "commas" that are the issue in preset names. The parser that reads the steps is pretty dumb so it sees every space as a step delimiter. Maybe I'll make a better editor that is more user friendly.
